apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd
  name: etcd-k8s
  namespace: kube-system
spec:
  ports:
  - name: port
    port: 2379
    protocol: TCP
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 121.32.250.66
    nodeName: master001
  - ip: 121.32.250.67
    nodeName: master002
  - ip: 121.32.250.68
    nodeName: master003
  ports:
  - name: port
    port: 2379
    protocol: TCP
