apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: grafana
   namespace: monitoring
   annotations:
     kubernetes.io/ingress.class: nginx

spec:
   rules:
   - host: k8s.grafana
     http:
       paths:
       - path: /
         backend:
          serviceName: grafana
          servicePort: 3000
   tls:
     - hosts:
         - k8s.grafana
       secretName: monitoring-certs