apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: prometheus
   namespace: monitoring
   annotations:
     kubernetes.io/ingress.class: nginx
spec:
   rules:
   - host: k8s.prometheus
     http:
       paths:
       - backend:
           service:
             name: prometheus-k8s
             port:
               number: 9090
         path: /
         pathType: ImplementationSpecific
   tls:
     - hosts:
         - k8s.prometheus
       secretName: monitoring-certs