apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook-adapter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-webhook-adapter
  template:
    metadata:
      labels:
        app: alertmanager-webhook-adapter
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.eks.net/infra
          operator: Exists
          effect: NoSchedule
      containers:
        - name: webhook
          image: registry-bj.capitalonline.net/eks/alertmanager-webhook-adapter:v1.1.7
          command:
            - /alertmanager-webhook-adapter
            - --listen-address=:8090
            - --signature=TEST
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 250Mi
              cpu: 500m
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook-adapter
  namespace: monitoring
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: alertmanager-webhook-adapter
  sessionAffinity: None
