apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICAKcm91dGU6CiAgZ3JvdXBfYnk6IFsnbmFtZXNwYWNlJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNjBzCiAgcmVwZWF0X2ludGVydmFsOiAzbQogIHJlY2VpdmVyOiAnd2ViaG9vaycKICAKcmVjZWl2ZXJzOgotIG5hbWU6ICd3ZWJob29rJwogIHdlYmhvb2tfY29uZmlnczoKICAtIHVybDogJ2h0dHA6Ly9jZHMtbW9uaXRvci10cmFuc2Zlci5rdWJlLXN5c3RlbTo2NjY2L3NlbmQnCiAgICBzZW5kX3Jlc29sdmVkOiB0cnVlCg==
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
