- job_name: monitoring/nvidia-gpu-exporter/0
  honor_labels: false
  kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
          - monitoring
  scrape_interval: 15s
  scheme: https
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
    - action: keep
      source_labels:
        - __meta_kubernetes_service_label_k8s_app
      regex: nvidia-gpu-exporter
    - action: keep
      source_labels:
        - __meta_kubernetes_endpoint_port_name
      regex: https
    - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
      separator: ;
      regex: Node;(.*)
      replacement: ${1}
      target_label: node
    - source_labels:
        - __meta_kubernetes_endpoint_address_target_kind
        - __meta_kubernetes_endpoint_address_target_name
      separator: ;
      regex: Pod;(.*)
      replacement: ${1}
      target_label: pod
    - source_labels:
        - __meta_kubernetes_namespace
      target_label: namespace
    - source_labels:
        - __meta_kubernetes_service_name
      target_label: service
    - source_labels:
        - __meta_kubernetes_pod_name
      target_label: pod
    - source_labels:
        - __meta_kubernetes_service_name
      target_label: job
      replacement: ${1}
    - source_labels:
        - __meta_kubernetes_service_label_k8s_app
      target_label: job
      regex: (.+)
      replacement: ${1}
    - target_label: endpoint
      replacement: https
    - source_labels:
        - __meta_kubernetes_pod_node_name
      target_label: instance
      regex: (.*)
      replacement: $1
      action: replace