apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nvidia-gpu-exporter
  name: nvidia-gpu-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nvidia-gpu-exporter
  template:
    metadata:
      labels:
        app: nvidia-gpu-exporter
    spec:
      containers:
      - name: dcgm-exporter
        #image: registry-bj.capitalonline.net/eks/dcgm-exporter:3.3.5-3.4.0
        image: capitalonline/dcgm-exporter:3.3.5-3.4.0
        env:
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        resources:
          limits:
            cpu: 250m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - name: "pod-gpu-resources"
            readOnly: true
            mountPath: "/var/lib/kubelet/pod-resources"
      - name: kube-rbac-proxy
        args:
        - --logtostderr
        - --secure-listen-address=[$(IP)]:9401
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - --upstream=http://127.0.0.1:9400/
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #image: registry-bj.capitalonline.net/cck/coreos/kube-rbac-proxy:v0.4.1
        image: capitalonline/kube-rbac-proxy:v0.4.1
        ports:
        - containerPort: 9401
          hostPort: 9401
          name: https
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
        node.kubernetes.io/gpu-type: NVIDIA
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: nvidia-gpu-exporter
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
      - hostPath:
          path: "/var/lib/kubelet/pod-resources"
        name: "pod-gpu-resources"