apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: kata-monitor
  name: kata-monitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
  jobLabel: name
  selector:
    matchLabels:
      name: kata-monitor
